local ADDON_NAME, addon = ...

local locale = GetLocale()
local isChinese = locale == "zhCN" or locale == "zhTW"

-- English strings are kept as keys so the original text remains available.
local translations = {
    ["Blacklist Warden"] = "黑名单守望者",
    ["Left click: |cffFFFFFFOpen player list"] = "左键点击：|cffFFFFFF打开玩家列表",
    ["Right click: |cffFFFFFFOpen settings"] = "右键点击：|cffFFFFFF打开设置",
    ["General Options"] = "常规选项",
    ["Toggle blacklist popup"] = "显示黑名单弹窗",
    ["Shows a popup when blacklisting a player that lets you add extra information, otherwise adds the player with default values."] = "将玩家加入黑名单时显示弹窗，以便添加额外信息；否则使用默认值添加玩家。",
    ["Lock windows"] = "锁定窗口",
    ["Locks the addon's windows, preventing them from moving."] = "锁定插件窗口，防止窗口被移动。",
    ["Toggle minimap icon"] = "显示小地图图标",
    ["Toggles the minimap icon."] = "显示或隐藏小地图图标。",
    ["Toggle leaver messages"] = "显示离队消息",
    ["Toggles a chat message when other players leave the group, which provides a link you can right click to make it easier to add leavers."] = "其他玩家离开队伍时在聊天窗口显示消息，其中包含可右键点击的链接，方便将离队玩家加入黑名单。",
    ["Credits"] = "鸣谢",
    ["|cffF58CBADiuxtros|r @ Icecrown (US) - |cffFF8000Author|r"] = "|cffF58CBADiuxtros|r @ Icecrown（美国）- |cffFF8000作者|r",
    ["All"] = "全部",
    ["Bad player"] = "菜",
    ["Quitter"] = "跳车",
    ["AFKer"] = "挂机",
    ["Toxic"] = "毒瘤",
    ["Scammer"] = "骗子",
    ["Bigot"] = "杠精",
    ["Other"] = "其他",
    ["Blacklist Warden: "] = "黑名单守望者：",
    ["]|r|h has left the group."] = "]|r|h 已离开队伍。",
    ["|cffFFFF00/blw settings -|r Opens the settings window"] = "|cffFFFF00/blw settings -|r 打开设置窗口",
    ["|cffFFFF00/blw list -|r Opens the list window"] = "|cffFFFF00/blw list -|r 打开列表窗口",
    [" added to blacklist."] = " 已加入黑名单。",
    [" successfully modified."] = " 已成功修改。",
    ["ADD TO BLACKLIST"] = "加入黑名单",
    ["EDIT"] = "编辑",
    [" removed from blacklist."] = " 已从黑名单移除。",
    ["Blacklist Warden - |rBlacklisted"] = "黑名单守望者 - |r已列入黑名单",
    ["Reason: |r"] = "原因：|r",
    ["Note: |r"] = "备注：|r",
    ["Blacklist player|r"] = "将玩家加入黑名单|r",
    ["Remove from blacklist|r"] = "从黑名单移除|r",
    ["Warrior"] = "战士",
    ["Paladin"] = "圣骑士",
    ["Hunter"] = "猎人",
    ["Rogue"] = "潜行者",
    ["Priest"] = "牧师",
    ["Shaman"] = "萨满祭司",
    ["Mage"] = "法师",
    ["Warlock"] = "术士",
    ["Monk"] = "武僧",
    ["Druid"] = "德鲁伊",
    ["Demon Hunter"] = "恶魔猎手",
    ["Death Knight"] = "死亡骑士",
    ["Evoker"] = "唤魔师",
    ["Leave"] = "离开",
    ["Stay"] = "留下",
    ["BLACKLISTED PLAYER"] = "已列入黑名单的玩家",
    ["Name:"] = "姓名：",
    ["Name: "] = "姓名：",
    ["Name"] = "姓名",
    ["Realm"] = "服务器",
    ["Class"] = "职业",
    ["Reason:"] = "原因：",
    ["Reason: "] = "原因：",
    ["Reason"] = "原因",
    ["Notes: \n"] = "备注：\n",
    ["Save"] = "保存",
    ["Cancel"] = "取消",
    ["Mute?"] = "屏蔽？",
    ["Note (optional):"] = "备注（可选）：",
    ["Close"] = "关闭",
    ["Player List"] = "玩家列表",
    ["Add player"] = "添加玩家",
    ["Date Added"] = "添加日期",
    ["Muted?"] = "已屏蔽？",
    ["Notes"] = "备注",
    ["ADD TO BLACKLIST: "] = "加入黑名单：",
    ["Realm:"] = "服务器：",
    ["Class:"] = "职业：",
    ["Add"] = "添加",
    ["Yes"] = "是",
    ["No"] = "否",
    ["Select option"] = "选择操作",
    ["Edit"] = "编辑",
    ["Remove"] = "移除",
    ["|cffFFFF00Blacklist Warden:|r Name or realm missing."] = "|cffFFFF00黑名单守望者：|r 缺少姓名或服务器。",
}

addon.L = setmetatable({}, {
    __index = function(_, english)
        if isChinese then
            return translations[english] or english
        end
        return english
    end,
})
